# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# # source: sending.proto
# """Generated protocol buffer code."""
# from google.protobuf.internal import builder as _builder
# from google.protobuf import descriptor as _descriptor
# from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import symbol_database as _symbol_database
# # @@protoc_insertion_point(imports)

# _sym_db = _symbol_database.Default()




# DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsending.proto\"w\n\x0bSendRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61ta_source\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x61taset_type\x18\x05 \x01(\t\x12\x12\n\nevent_type\x18\x06 \x01(\t\"\x1f\n\x0cSendResponse\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\tSenderCSV\x12)\n\x08SendFile\x12\x0c.SendRequest\x1a\r.SendResponse\"\x00\x62\x06proto3')

# _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
# _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sending_pb2', globals())
# if _descriptor._USE_C_DESCRIPTORS == False:

#   DESCRIPTOR._options = None
#   _SENDREQUEST._serialized_start=17
#   _SENDREQUEST._serialized_end=136
#   _SENDRESPONSE._serialized_start=138
#   _SENDRESPONSE._serialized_end=169
#   _SENDERCSV._serialized_start=171
#   _SENDERCSV._serialized_end=225
# @@protoc_insertion_point(module_scope)
